# Exercise 11.3

name: Hello World!

on:
   push:
      branches:
         - master

jobs:
   hello_world_job:
      runs-on: ubuntu-20.04
      steps:
         - name: Hello
           run: |
              echo "Hello world!"
              date
              ls
