name: Hello World!

on:
   push:
      branches:
         - master

jobs:
   hello_world_job:
      runs-on: ubuntu-20.04 windows-10
      steps:
         - name: Hello
           run: |
              echo "Hello world!"
