name: Version bump

on:
   pull_request:
      types:
         - closed
      branches:
         - master

jobs:
   versioning:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-20.04
      permissions:
         contents: write
      steps:
         - uses: actions/checkout@v3
           with:
              ref: ${{github.event.pull_request.merge_commit_sha}}
              fetch-depth: "0"

         - name: Bump version and create tag
           uses: anothrNick/github-tag-action@1.67.0
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              WITH_V: true
              DEFAULT_BUMP: patch
